name: binary-waterfall
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10*
  - pip
  - pip:
    - pyinstaller
    - pyinstaller-versionfile
    - PyQt5
    - pydub
    - Pillow
    - moviepy
    - proglog